# Discover catalog and template IDs at:
# https://labs.opentlc.com/api/service_catalogs?expand=resources
# https://labs.opentlc.com/api/service_templates?expand=resources
#
# Discover the mandatory dialog parameters for the service after manually provisioning the service:
# https://labs.opentlc.com/api/service_requests?expand=resources
#
# Or provision the lab manually and then list the parameteres using:
# ansible-playbook -i inventory/localhost.yml otlc_provisioned_services.yml
#
# Discover custom actions (like Start, extend lifetime) for the service along with the respective dialog ids, example:
# https://labs.opentlc.com/api/services/20000000423849?attributes=custom_actions,custom_action_buttons
#
# Discover mandatory dialog parameters for custom actions dialogs at:
# https://labs.opentlc.com/api/service_dialogs/20000000000031
#
# ManageIQ API documentation:
# https://www.manageiq.org/docs/api
#
# Possible dialog_region values:
# na_sandbox_gpte
# emea_sandbox_gpte
# apac_sandbox_gpte
#
# na
# na2
# emea
#
# Labs not managed by Ansible:
# ODF 4 Implementation - runs on OpenStack, was able to only add one extra node

otlc_labs:
  # OCP 4.5.4, cannot add records to the DNS zone, shuts down after 8 hours, deleted after 2 days, RHACM 2.0.3 preinstalled
  acm_foundation_hub:
    catalog_id: '20000000000040'
    template_name: 'OPENTLC OpenShift 4 Labs'
    template_id: '20000000000859'
    catalog_name: 'OpenShift 4 ACM Foundation Lab (Hub)'
    order_options:
      dialog_expiration: "2"
      dialog_region: na_sandbox_gpte
      dialog_runtime: "8"
      dialog_notes: "Customer Activity - Customer environment testing"
      dialog_environment: PROD

  # OCP 4.4.29, cannot add records to the DNS zone, shuts down after 8 hours, deleted after 2 days
  acm_foundation_managed:
    catalog_id: '20000000000040'
    template_name: 'OPENTLC OpenShift 4 Labs'
    template_id: '20000000000860'
    catalog_name: 'OpenShift 4 ACM Foundation Lab (Managed)'
    order_options:
      dialog_check: t
      dialog_expiration: "2"
      dialog_region: na_sandbox_gpte
      dialog_runtime: "8"
      dialog_notes: "Customer Activity - Customer environment testing"
      dialog_environment: PROD

  ocp3_migration:
    catalog_id: '20000000000040'
    catalog_name: 'OPENTLC OpenShift 4 Labs'
    template_id: '20000000000653'
    template_name: 'OCP Migration Lab - OCP 3 Cluster'
    order_options:
      dialog_expiration: "7"
      dialog_nodes: "3"
      dialog_ocprelease: 3.11.346
      dialog_region: na
      dialog_runtime: "8"
      dialog_notes: "Customer Activity - Informal training"
      dialog_environment: PROD

  ocp4_migration:
    catalog_id: '20000000000040'
    catalog_name: 'OPENTLC OpenShift 4 Labs'
    template_id: '20000000000652'
    template_name: 'OCP Migration Lab - OCP 4 Cluster'
    order_options:
      dialog_check: t
      dialog_expiration: "7"
      dialog_region: na_sandbox_gpte
      dialog_runtime: "10"
      dialog_notes: "Customer Activity - Informal training"
      dialog_environment: PROD

  ocp4_clientvm:
    catalog_id: '20000000000040'
    catalog_name: 'OPENTLC OpenShift 4 Labs'
    template_id: '20000000000610'
    template_name: 'OpenShift 4 Client VM'
    order_options:
      dialog_expiration: "7"
      dialog_ocprelease: "4.3.0"
      dialog_region: na
      dialog_runtime: "8"

  ocp4_shared_access:
    catalog_id: '20000000000040'
    catalog_name: 'OPENTLC OpenShift 4 Labs'
    template_id: '20000000000607'
    template_name: 'OPENTLC OpenShift 4 Shared Access'
    order_options:
      dialog_check: t
      dialog_environment: PROD
      dialog_expiration: "7"
      dialog_region: na_opentlc
      dialog_runtime: "8"

  # Custom OCP installation, TLS certs configuration works, runs constantly, AWS
  ocp4_installation:
    catalog_id: '20000000000040'
    catalog_name: 'OPENTLC OpenShift 4 Labs'
    template_id: '20000000001005'
    template_name: 'OpenShift 4 Installation Lab'
    order_options:
      dialog_environment: PROD
      dialog_expiration: "6"
      dialog_notes: "Customer Activity - Customer environment testing"
      dialog_region: emea_sandbox_gpte
      dialog_runtime: "8"

  # Cannot add records to the DNS zone, shuts down after 8 hours
  ocp4_configuration:
    catalog_id: '20000000000040'
    catalog_name: 'OPENTLC OpenShift 4 Labs'
    template_id: '20000000000741'
    template_name: 'OpenShift 4 Configuration Lab'
    order_options:
      dialog_check: t
      dialog_environment: PROD
      dialog_expiration: "7"
      dialog_notes: "Customer Activity - Customer environment testing"
      dialog_region: na_sandbox_gpte
      dialog_runtime: "8"

  # OCP 4.8.2, single-node control plane, Let's Encrypt TLS certs, shuts down after 4 hours, AWS
  ocp4_handson_48:
    catalog_id: '20000000000040'
    catalog_name: 'OPENTLC OpenShift 4 Labs'
    template_id: '20000000001027'
    template_name: 'Hands On with OpenShift 4.8'
    order_options:
      dialog_check: t
      dialog_environment: PROD
      dialog_expiration: "7"
      dialog_notes: "Customer Activity - Customer environment testing"
      dialog_region: na_sandbox_gpte
      dialog_runtime: "8"

  # OCP 4.9.15, single-node cluster, Let's Encrypt TLS certs, shuts down after 4 hours, AWS
  ocp4_handson_49:
    catalog_id: '20000000000040'
    catalog_name: 'OPENTLC OpenShift 4 Labs'
    template_id: '20000000001044'
    template_name: 'Hands On with OpenShift 4.9'
    order_options:
      dialog_accept: t
      dialog_environment: PROD
      dialog_expiration: "7"
      dialog_notes: "Training - Ad-hoc or exploratory"
      dialog_region: na_sandbox_gpte
      dialog_runtime: "8"

  # OCP 4.7.4, cannot add records to the DNS zone, Let's Encrypt TLS certs, shuts down after 8 hours, AWS
  ocs4_implementation:
    catalog_id: '20000000000040'
    catalog_name: 'OPENTLC OpenShift 4 Labs'
    template_id: '20000000000951'
    template_name: 'OCS 4 Implementation on AWS'
    order_options:
      dialog_check: t
      dialog_environment: PROD
      dialog_expiration: "7"
      dialog_region: na
      dialog_notes: "Customer Activity - Customer environment testing"
      dialog_runtime: "8"

  # OCP 4.7.16, cannot add records to the DNS zone, Let's Encrypt TLS certs, shuts down after 8 hours, AWS
  ossm_lab:
    catalog_id: '20000000000040'
    catalog_name: 'OPENTLC OpenShift 4 Labs'
    template_id: '20000000001015'
    template_name: 'OpenShift 4 Service Mesh Lab'
    order_options:
      dialog_accept: t
      dialog_environment: PROD
      dialog_expiration: "7"
      dialog_region: na_sandbox_gpte
      dialog_notes: "Development - Solution prototyping"
      dialog_runtime: "8"

  rhel7_implementation:
    catalog_id: '20000000000001'
    catalog_name: 'OPENTLC Datacenter Infrastructure Labs'
    template_id: '20000000000703'
    template_name: 'RHEL 7 Implementation Lab'
    order_options:
      dialog_check: t
      dialog_environment: PROD
      dialog_expiration: "7"
      dialog_region: na_osp
      dialog_notes: "Customer Activity - Customer environment testing"
      dialog_runtime: "4"

  rhel8_beta:
    catalog_id: '20000000000001'
    catalog_name: 'OPENTLC Datacenter Infrastructure Labs'
    template_id: '20000000000709'
    template_name: 'RHEL 8 New Features For Exp. Admins'
    order_options:
      dialog_check: t
      dialog_environment: PROD
      dialog_expiration: "4"
      dialog_region: na_osp
      dialog_notes: "Customer Activity - Customer environment testing"
      dialog_runtime: "8"

  rhev:
    catalog_id: '20000000000001'
    catalog_name: 'OPENTLC Datacenter Infrastructure Labs'
    template_id: '20000000000290'
    template_name: 'RHV 4.0 Foundations Lab'
    order_options:
      dialog_check: t
      dialog_expiration: "7"
      dialog_runtime: "4"
